apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: pmirshah/Pnorve2/template:latest 
          ports:
            - containerPort: 80
          # env:
          #   - name: 
          #     value: "value"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # The port inside the container
  type: LoadBalancer # Expose to the internet (use ClusterIP for internal services only)
